### ISSUE TITLE
Settings for Cifar10 dataset

### ISSUE THREAD

**Issue by aprilbian** [wsxtyrdd/NTSCC_JSAC22#1]
Hi sixian:

  Thanks a lot for the nice work! I am recently trying to re-implement it for the CIFAR10 dataset. I found that by setting lambda = {1024, 256, 64, 16, 4} for the CIFAR10 as shown in the JSAC paper  does not give me the same performance in Fig.9 (a). To be specific, setting lambda = 4 gives me a PSNR ~ 34 dB at SNR = 10dB while setting lambda = 64 yields PSNR ~ 33.5 dB. 

  Could you please inform me how to obtain the CIFAR 10 performance in Fig. 9 (a)? By setting even smaller lambda (e.g., 0.1) for good PSNR and setting very large lambda (e.g., 10k) to obtain low bit rate? Or one should simply change the eta from 0.2 to some other values?

  Thanks a lot in advance!

**Comment by wsxtyrdd** [comment]
Hi aprilbian, thank you for your comment. Please compare your re-implementated model with other schemes in Fig. 9(a) in terms of CBR-PSNR, simply checking PSNR is not sufficient. You can first fix eta and lambda (e.g., 4 and 0.2) to obtain a point on the RD curve, and then fine-tune to other points.

**Comment by aprilbian** [comment]
Thanks for the response!
