### ISSUE TITLE
How to install requirements.txt

### ISSUE THREAD

**Issue by aomenfage** [wsxtyrdd/NTSCC_JSAC22#2]
Hi, I’m having some issues with installing the requirements for your project. When I run `python -m pip install -r requirements.txt`, I get this error: `ERROR: Invalid requirement: '_libgcc_mutex=0.1=conda_forge' (from line 4 of requirements.txt)`. And when I run `conda create --name zxy --file requirements.txt,` I get this error: `PackagesNotFoundError: The following packages are not available from current channels:`.
Could you please help me resolve these errors? Thank you.

**Comment by wsxtyrdd** [comment]
Hi, I have removed the unnecessary requirements now. Please follow the updated requirements. Thanks for your feedback.
