### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by dongbiao321** [wsxtyrdd/NTSCC_JSAC22#3]
train_data_dir = ['path to DIV2K_train_HR or OpenImages']
test_data_dir = ['Path to kodak']
paper mention that "the dataset for training the proposed NTSCC model for large images consists of 500,000 images sampled from the Open Images Dataset".  What is the difference in permance between DIV2K_train_HR  and OpenImages? The size of DIV2K_train_HR  is about 900, while the size of OpenImages is 500,000.

**Comment by wsxtyrdd** [comment]
Both DIV2K_train_HR and Open Images datasets are viable options for training the NTSCC model. In my experiments, satisfactory results were achieved with both datasets, as well as with Flickr dataset.
