### ISSUE TITLE
Question about the channel and channel coding

### ISSUE THREAD

**Issue by tuning12** [wsxtyrdd/NTSCC_JSAC22#4]
Thank you for your great work!!
I have some questions about the channel coding and the channel. First, I havn't seen the implementation of channel coding in your code. Besides, the channel seems to directly add a complex gaussian noise on the quantified vector without coding and modulation. The above two issues are different from the paper. I wonder if there are some details I havn't notice.

**Comment by wsxtyrdd** [comment]
As a joint source channel codec, NTSCC directly learns the mapping from RGB domain to channel input symbols. The variable-length latents are robust enough, which will be power normalized and sent to the receiver.

**Comment by tuning12** [comment]
Thank you for your reply.
