### ISSUE TITLE
question about the baseline

### ISSUE THREAD

**Issue by tuning12** [wsxtyrdd/NTSCC_JSAC22#5]
Thank you for your great work!
Could you please provide your source codes of BPD+LDPC+QAM?

**Comment by wsxtyrdd** [comment]
Please refer to https://github.com/kmsiapps/Semantic-Communications-with-a-Vision-Transformer/blob/main/bpg-ldpc.ipynb
LDPC+QAM is implemented based on sionna. The simulation details can be found at the appendix of https://arxiv.org/abs/2303.14637

**Comment by tuning12** [comment]
thank you for your reply!
