### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by Yinhance** [wsxtyrdd/NTSCC_JSAC22#6]
When I run
`python main.py -p train`, there is a error:
`RuntimeError: Expected isFloatingType(grad.scalar_type()) || (input_is_complex == grad_is_complex) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)`
I checked the Gradient but output False.

> for batch_idx, input_image in enumerate(train_loader):
>         optimizer_G.zero_grad()
>         aux_optimizer.zero_grad()
>         start_time = time.time()
>         input_image = input_image.to(device)
>         global_step += 1
>         mse_loss_ntc, bpp_y, bpp_z, mse_loss_ntscc, cbr_y, x_hat_ntc, x_hat_ntscc = net(input_image)
>         if config.use_side_info: # False
>             cbr_z = bpp_snr_to_kdivn(bpp_z, 10)
>             loss = mse_loss_ntscc + mse_loss_ntc + config.train_lambda * (bpp_y * config.eta + cbr_z)
>             cbrs.update(cbr_y + cbr_z)
>         else:
>             # add ntc_loss to improve the training convergence stability
>             ntc_loss = mse_loss_ntc + config.train_lambda * (bpp_y + bpp_z)
>             loss = ntc_loss + mse_loss_ntscc
>             cbrs.update(cbr_y)
>         print("Input Image Type:", input_image.dtype)
>         print("Gradient Exists:", any(p.grad is not None for p in net.parameters()))

How to solve this promblem? Thx a lot :)

**Comment by wsxtyrdd** [comment]
1. Please check whether complex grad is supported in your torch version. 
2. I find the gradient is wrong when training includes torch.masked_select function, please refer to https://github.com/pytorch/pytorch/issues/99638 
3. Please switch to another channel realization to avoid the gradient bug when you need to train your own NTSCC.
